import { describe, expect, it } from 'vitest';
import { AgentMemory, experienceDeltaForVisits, wallExperienceDeltaForAttempts } from '@/agent/memory';
import { buildLocalAgentPrompt, getDirectionChoices } from '@/agent/prompt';
import { Maze } from '@/maze/maze';
const lineMaze=()=>new Maze(['#######','#S   G#','#######']);
describe('sensor-driven EiL mouse',()=>{
 it('uses exact open and wall experience curves',()=>{expect([0,1,2,3,4,5,6,7,8,9].map(experienceDeltaForVisits)).toEqual([2,0,-2,-4,-8,-16,-32,-64,-128,-128]);expect([0,1,2,3,4,5,6,7,8].map(wallExperienceDeltaForAttempts)).toEqual([-2,-4,-8,-16,-32,-64,-128,-128,-128]);});
 it('keeps sight separate from visit memory',()=>{const m=new AgentMemory();const maze=lineMaze();m.rememberPerception(maze.perceive({x:1,y:1}),true);const s=m.snapshot();expect(s.seen).toContain('2,1');expect(s.visited).toEqual(['1,1']);expect(s.newlySeen).toContain('2,1');});
 it('calculates smell around walls through reachable cells',()=>{const maze=new Maze(['#########','#S#    G#','# #     #','#       #','#########']);expect(maze.smellAt({x:7,y:1})).toBe(101);expect(maze.smellAt({x:6,y:1})).toBe(100);expect(maze.smellAt({x:5,y:1})).toBe(99);expect(maze.smellAt({x:2,y:1})).toBe(0);});
 it('applies wall collision without moving and normal move without touch damage',()=>{const maze=lineMaze();const m=new AgentMemory();m.rememberPerception(maze.perceive({x:1,y:1}),true);const wall=m.evaluate(maze.perceive({x:1,y:1}),'up');m.rememberAction({from:{x:1,y:1},move:'up',succeeded:false,to:{x:1,y:1},message:'wall',effects:wall});expect(m.snapshot().health).toBe(90);expect(wall.touchDelta).toBe(-100);const open=m.evaluate(maze.perceive({x:1,y:1}),'right');m.rememberAction({from:{x:1,y:1},move:'right',succeeded:true,to:{x:2,y:1},message:'open',effects:open});expect(m.snapshot().health).toBe(90);});
 it('decays health after 20 successful physical cells',()=>{const maze=lineMaze();const m=new AgentMemory();m.rememberPerception(maze.perceive({x:1,y:1}),true);for(let i=0;i<20;i++)m.rememberAction({from:{x:1,y:1},move:'right',succeeded:true,to:{x:2,y:1},message:'step',effects:{...m.evaluate(maze.perceive({x:1,y:1}),'right'),totalExpectedEiLDelta:0}});expect(m.snapshot().physicalSteps).toBe(20);expect(m.snapshot().health).toBe(95);});
 it('applies one-time EiL health thresholds and can leave 1% health',()=>{const maze=lineMaze();const m=new AgentMemory();m.rememberPerception(maze.perceive({x:1,y:1}),true);for(let i=0;i<4;i++)m.rememberAction({from:{x:1,y:1},move:'right',succeeded:true,to:{x:2,y:1},message:'drop',effects:{...m.evaluate(maze.perceive({x:1,y:1}),'right'),totalExpectedEiLDelta:-128}});expect(m.snapshot().eil.score).toBe(0);expect(m.snapshot().health).toBe(1);const before=m.snapshot().health;m.rememberAction({from:{x:1,y:1},move:'right',succeeded:true,to:{x:2,y:1},message:'low',effects:{...m.evaluate(maze.perceive({x:1,y:1}),'right'),totalExpectedEiLDelta:0}});expect(m.snapshot().health).toBe(before);});
 it('builds compact semantic prompt and keeps walls selectable',()=>{const maze=lineMaze();const m=new AgentMemory();const p=maze.perceive({x:1,y:1});m.rememberPerception(p,true);const prompt=buildLocalAgentPrompt(p,m.snapshot());expect(prompt).toContain('Health: 100%');expect(prompt).toContain('EiL: 500 / 1000');for(const word of ['Touch','Experience','Visited','Sight','Smell','expected to']){expect(prompt).toContain(word);}expect(prompt).not.toContain('visit count');expect(prompt).not.toContain('101');expect(prompt).not.toContain('JUMP');expect(getDirectionChoices(p,m.snapshot()).find(c=>c.direction==='up')?.blocked).toBe(true);});
});
