export type EiLTrend = 'rising' | 'falling' | 'stable';
export type EiLScale = 'signed' | 'normalized' | 'positive100';
export type EiLState = { score: number; label: string; lastReward: number; trend: EiLTrend };
export const MIN_SCORE = 0; export const MAX_SCORE = 1000; export const START_SCORE = 500; export const DEFAULT_EIL_SCALE: EiLScale = 'positive100';
export function emotionalLabel(score: number): string { if (score >= 900) return 'EXTREMELY HAPPY'; if (score >= 700) return 'HAPPY'; if (score >= 501) return 'POSITIVE'; if (score === 500) return 'NEUTRAL'; if (score >= 301) return 'UNHAPPY'; if (score >= 101) return 'VERY UNHAPPY'; return 'CRITICAL'; }
export function convertEiLScore(score: number, scale: EiLScale): number { if (scale === 'normalized') return Math.max(0, Math.min(1, score / MAX_SCORE)); if (scale === 'positive100') return Math.max(0, Math.min(100, score / 10)); return score; }
export function convertToSignedScore(score: number, scale: EiLScale): number { if (scale === 'normalized') return score * MAX_SCORE; if (scale === 'positive100') return score * 10; return score; }
export function formatEiLScore(score: number, scale: EiLScale = DEFAULT_EIL_SCALE): string { if (scale === 'normalized') return convertEiLScore(score, scale).toFixed(3); if (scale === 'positive100') return convertEiLScore(score, scale).toFixed(0); return String(Math.round(score)); }
export function formatEiLMaximum(scale: EiLScale = DEFAULT_EIL_SCALE): string { return scale === 'normalized' ? '1.000' : scale === 'positive100' ? '100' : '1000'; }
export class EiL { private score = START_SCORE; private lastReward = 0; private trend: EiLTrend = 'stable'; public reset(): void { this.score = START_SCORE; this.lastReward = 0; this.trend = 'stable'; } public apply(reward: number): EiLState { this.lastReward = reward; this.trend = reward > 0 ? 'rising' : reward < 0 ? 'falling' : 'stable'; this.score = Math.max(MIN_SCORE, Math.min(MAX_SCORE, this.score + reward)); return this.snapshot(); } public reachGoal(): EiLState { return this.apply(MAX_SCORE - this.score); } public snapshot(): EiLState { return { score: this.score, label: emotionalLabel(this.score), lastReward: this.lastReward, trend: this.trend }; } }
