import { EiL, type EiLState } from '@/agent/eil';
import type { Move } from '@/execution/execution';
import type { LocalPerception, Position } from '@/maze/maze';
export type SensorEffect = { touchDelta:number; smellDelta:number; sightDelta:number; experienceDelta:number; totalExpectedEiLDelta:number; touch:string; smell:string; sight:string; experience:string; visited:string; destination:Position; wall:boolean };
export type ActionObservation = { from:Position; move:Move; succeeded:boolean; to:Position; message:string; goalReached?:boolean; actionLabel?:string; effects?:SensorEffect };
export type AgentMemoryState = { seen:string[]; newlySeen:string[]; visited:string[]; visitCounts:Record<string,number>; locationScores:Record<string,number>; walls:string[]; wallAttempts:Record<string,number>; failedActions:string[]; route:string[]; recentObservations:string[]; eil:EiLState; health:number; physicalSteps:number; actionEffects:Partial<Record<Move,SensorEffect>>; eil100HealthPenaltyApplied:boolean; eil50HealthPenaltyApplied:boolean; eil0HealthPenaltyApplied:boolean };
const key=(p:Position)=>`${p.x},${p.y}`;
const experienceValues=[2,0,-2,-4,-8,-16,-32,-64,-128];
export const experienceDeltaForVisits=(visits:number)=>experienceValues[Math.min(8,Math.max(0,visits))];
export const wallExperienceDeltaForAttempts=(attempts:number)=>-Math.min(128,2**(Math.max(0,attempts)+1));
export const experienceLabel=(delta:number)=>delta>=2?'ATTRACTIVE':delta===0?'NEUTRAL':delta>=-2?'SLIGHTLY AVERSIVE':delta>=-8?'AVERSIVE':delta>=-32?'STRONGLY AVERSIVE':'EXTREMELY AVERSIVE';
export const visitedLabel=(visits:number)=>visits===0?'No, New Location':visits===1?'Yes':visits===2?'Yes, More Than Once':'Yes, Multiple Times';
export class AgentMemory {
 private readonly seen=new Set<string>(); private readonly newlySeen=new Set<string>(); private readonly visited=new Set<string>(); private readonly visitCounts=new Map<string,number>(); private readonly walls=new Set<string>(); private readonly wallAttempts=new Map<string,number>(); private readonly failedActions:string[]=[]; private readonly route:string[]=[]; private readonly recentObservations:string[]=[]; private readonly locationScores=new Map<string,number>(); private readonly eil=new EiL(); private readonly actionEffects:Partial<Record<Move,SensorEffect>>={}; private health=100; private physicalSteps=0; private threshold100=false; private threshold50=false; private threshold0=false;
 public constructor(_now:()=>number=Date.now) {}
 public reset():void{this.seen.clear();this.newlySeen.clear();this.visited.clear();this.visitCounts.clear();this.walls.clear();this.wallAttempts.clear();this.failedActions.length=0;this.route.length=0;this.recentObservations.length=0;this.locationScores.clear();for(const move of ['up','down','left','right'] as Move[])delete this.actionEffects[move];this.eil.reset();this.health=100;this.physicalSteps=0;this.threshold100=this.threshold50=this.threshold0=false;}
 public rememberPerception(perception:LocalPerception,recordCurrentVisit=false):void{for(const cell of [{position:perception.position},...perception.visibleCells]){const k=key(cell.position);if(!this.seen.has(k))this.newlySeen.add(k);this.seen.add(k);}if(recordCurrentVisit)this.recordVisit(perception.position);for(const [direction,state] of Object.entries(perception.directions))if(state==='wall')this.walls.add(`${key(perception.position)}:${direction}`);for(const move of ['up','down','left','right'] as Move[])this.actionEffects[move]=this.evaluate(perception,move);}
 public recordVisit(position:Position):void{const k=key(position);this.visited.add(k);this.visitCounts.set(k,(this.visitCounts.get(k)??0)+1);}
 public evaluate(perception:LocalPerception,move:Move):SensorEffect{const destination={x:perception.position.x+(move==='left'?-1:move==='right'?1:0),y:perception.position.y+(move==='up'?-1:move==='down'?1:0)};const destinationKey=key(destination);const wall=perception.directions[move]==='wall';const visits=this.visitCounts.get(destinationKey)??0;const wallKey=`${key(perception.position)}:${move}`;const attempts=this.wallAttempts.get(wallKey)??0;const experienceDelta=wall?wallExperienceDeltaForAttempts(attempts):experienceDeltaForVisits(visits);const currentSmell=perception.smell;const destinationSmell=perception.directionSmell[move]??0;const smellDelta=wall?-10:destinationSmell>currentSmell?10:destinationSmell<currentSmell?-10:0;const sightDelta=this.newlySeen.has(destinationKey)?10:0;return{destination,wall,touchDelta:wall?-100:0,smellDelta,sightDelta,experienceDelta,totalExpectedEiLDelta:(wall?-100:0)+smellDelta+sightDelta+experienceDelta,touch:wall?'Negative Health Effect':'No Health Effect',smell:wall?'No Smell':smellDelta>0?'Increase Smell':smellDelta<0?'Decrease Smell':'Same Smell',sight:sightDelta?'New':'Already Seen',experience:experienceLabel(experienceDelta),visited:visitedLabel(visits)};}
 public rememberAction(observation:ActionObservation):void{const effects=observation.effects;const before=this.eil.snapshot().score;if(observation.succeeded){this.recordVisit(observation.to);this.physicalSteps++;if(this.physicalSteps%20===0)this.applyHealth(-5);}else{const wallKey=`${key(observation.from)}:${observation.actionLabel??observation.move}`;this.walls.add(wallKey);this.wallAttempts.set(wallKey,(this.wallAttempts.get(wallKey)??0)+1);this.applyHealth(-10);}if(observation.goalReached)this.eil.reachGoal();else this.eil.apply(effects?.totalExpectedEiLDelta??(observation.succeeded?0:-110));this.applyEiLThresholds(before,this.eil.snapshot().score);this.route.push(key(observation.from));if(observation.succeeded)this.route.push(key(observation.to));if(!observation.succeeded)this.failedActions.unshift(`${key(observation.from)}:${observation.actionLabel??observation.move}`);this.recentObservations.unshift(observation.message);this.recentObservations.splice(8);this.newlySeen.clear();}
 public snapshot():AgentMemoryState{return{seen:[...this.seen],newlySeen:[...this.newlySeen],visited:[...this.visited],visitCounts:Object.fromEntries(this.visitCounts),locationScores:Object.fromEntries(this.locationScores),walls:[...this.walls],wallAttempts:Object.fromEntries(this.wallAttempts),failedActions:[...this.failedActions].slice(0,12),route:[...this.route].slice(-12),recentObservations:[...this.recentObservations],eil:this.eil.snapshot(),health:this.health,physicalSteps:this.physicalSteps,actionEffects:{...this.actionEffects},eil100HealthPenaltyApplied:this.threshold100,eil50HealthPenaltyApplied:this.threshold50,eil0HealthPenaltyApplied:this.threshold0};}
 private applyHealth(delta:number):void{this.health=Math.max(0,Math.min(100,this.health+delta));}
 private applyEiLThresholds(before:number,after:number):void{if(!this.threshold100&&before>100&&after<=100){this.threshold100=true;this.applyHealth(-33);}if(!this.threshold50&&before>50&&after<=50){this.threshold50=true;this.applyHealth(-33);}if(!this.threshold0&&before>0&&after===0){this.threshold0=true;this.applyHealth(-33);}}
}
