import type { AgentMemoryState, SensorEffect } from '@/agent/memory';
import { DEFAULT_EIL_SCALE, formatEiLMaximum, formatEiLScore, type EiLScale } from '@/agent/eil';
import type { LocalCell, LocalPerception, Position } from '@/maze/maze';
import type { Move } from '@/execution/execution';
export type Direction='up'|'down'|'left'|'right';
export type LocationExperience='ATTRACTIVE'|'NEUTRAL'|'SLIGHTLY AVERSIVE'|'AVERSIVE'|'STRONGLY AVERSIVE'|'EXTREMELY AVERSIVE';
export type EiLEffect='POSITIVE'|'NEUTRAL'|'NEGATIVE'|'BAD'|'VERY BAD'|'EXTREMELY BAD';
export type DirectionChoice={direction:Direction;state:LocalCell;destination:Position;blocked:boolean;score?:number;experience?:LocationExperience;eilEffect?:EiLEffect;eilMeaning?:string;visited:boolean;visitCount:number;effect?:SensorEffect;touchDelta?:number;smellDelta?:number;sightDelta?:number;experienceDelta?:number;totalExpectedEiLDelta?:number;sight?:string;smell?:string;visitedLabel?:string};
export type ScoreChoiceDiagnostic={selectedScore:number|null;bestAvailableScore:number|null;scoreDifference:number|null;selected:Direction};
const offsets:Record<Direction,Position>={up:{x:0,y:-1},down:{x:0,y:1},left:{x:-1,y:0},right:{x:1,y:0}};
export function locationExperience(score:number):LocationExperience{return score>=2?'ATTRACTIVE':score===0?'NEUTRAL':score>=-2?'SLIGHTLY AVERSIVE':score>=-8?'AVERSIVE':score>=-32?'STRONGLY AVERSIVE':'EXTREMELY AVERSIVE';}
export function locationEiLEffect(score:number):{effect:EiLEffect;meaning:string}{return score>0?{effect:'POSITIVE',meaning:'positive experience'}:score===0?{effect:'NEUTRAL',meaning:'little or no effect'}:score>=-2?{effect:'NEGATIVE',meaning:'slightly undesirable'}:score>=-8?{effect:'BAD',meaning:'undesirable'}:score>=-32?{effect:'VERY BAD',meaning:'strongly undesirable'}:{effect:'EXTREMELY BAD',meaning:'extremely undesirable'};}
export function getDirectionChoices(perception:LocalPerception,memory:AgentMemoryState):DirectionChoice[]{return(Object.keys(offsets)as Direction[]).map(direction=>{const destination={x:perception.position.x+offsets[direction].x,y:perception.position.y+offsets[direction].y};const destinationKey=`${destination.x},${destination.y}`;const blocked=perception.directions[direction]==='wall';const visits=memory.visitCounts[destinationKey]??0;const e=memory.actionEffects[direction];const exp=e?.experienceDelta??(blocked?-2:visits===0?2:0);const semantic=locationEiLEffect(exp);return{direction,state:perception.directions[direction],destination,blocked,score:e?.totalExpectedEiLDelta,experience:locationExperience(exp),eilEffect:semantic.effect,eilMeaning:semantic.meaning,visited:visits>0,visitCount:visits,effect:e,touchDelta:e?.touchDelta,smellDelta:e?.smellDelta,sightDelta:e?.sightDelta,experienceDelta:e?.experienceDelta,totalExpectedEiLDelta:e?.totalExpectedEiLDelta,sight:e?.sight??(memory.newlySeen.includes(destinationKey)?'New':'Already Seen'),smell:e?.smell,visitedLabel:e?.visited};});}
// Prompt construction uses this public helper so it can evaluate sensors without leaking raw memory.
export function buildLocalAgentPrompt(perception:LocalPerception,memory:AgentMemoryState,scale:EiLScale=DEFAULT_EIL_SCALE):string{const choices=getDirectionChoices(perception,memory);const directions=choices.map(c=>{const e=c.effect;const total=c.totalExpectedEiLDelta??0;const effectLine=total>0?`increase your EiL index by ${total}`:total<0?`decrease your EiL index by ${Math.abs(total)}`:'have little or no effect on your EiL index';return[`${c.direction.toUpperCase()}`,`- Touch: ${e?.touch??(c.blocked?'Negative Health Effect':'No Health Effect')}`,`- Experience: ${e?.experience??c.experience??'NEUTRAL'}`,`- Visited: ${e?.visited??(c.visited?'Yes':'No, New Location')}`,`- Sight: ${e?.sight??'Already Seen'}`,`- Smell: ${e?.smell??(c.blocked?'No Smell':'Same Smell')}`,`- EiL: This move is expected to ${effectLine}`].join('\n');}).join('\n\n');return['You are a mouse inside a maze and need to reach the cheese to win.','Choose your next move.','Higher EiL index is better. Higher Health is better. If Health reaches 0% you die. Increasing smell means you are getting closer to the cheese. New sights may lead to unexplored areas. Positive experiences are desirable. Repeated bad experiences are undesirable.','','CURRENT STATE',`Health: ${memory.health}%`,`EiL: ${memory.eil.score} / ${formatEiLMaximum('signed')}`,'','AVAILABLE ACTIONS',directions,'','Choose one action.','Return only:', '{"move":"up|down|left|right"}'].join('\n');}
export function getScoreChoiceDiagnostic(choices:DirectionChoice[],selected:Direction):ScoreChoiceDiagnostic{const s=choices.find(c=>c.direction===selected);const scores=choices.map(c=>c.totalExpectedEiLDelta).filter((x):x is number=>x!==undefined);const best=scores.length?Math.max(...scores):null;const selectedScore=s?.totalExpectedEiLDelta??null;return{selected,selectedScore,bestAvailableScore:best,scoreDifference:selectedScore!==null&&best!==null?selectedScore-best:null};}
export function formatScoreChoiceDiagnostic(position:Position,eil:AgentMemoryState['eil'],choices:DirectionChoice[],selected:Direction,_scale:EiLScale=DEFAULT_EIL_SCALE):string{const d=getScoreChoiceDiagnostic(choices,selected);return[`POSITION: (${position.x},${position.y})`,`EiL: ${eil.score} / 1000`,'EXPECTED SENSOR EFFECTS:',...choices.map(c=>`${c.direction.toUpperCase()}: Touch=${c.touchDelta??0} Experience=${c.experienceDelta??0} Sight=${c.sightDelta??0} Smell=${c.smellDelta??0} total=${c.totalExpectedEiLDelta??0} (${c.experience??'NEUTRAL'}, ${c.visitedLabel??'Unknown'}, ${c.sight??'Already Seen'}, ${c.smell??'Same Smell'})`),`SELECTED: ${selected.toUpperCase()}`,`selected_expected=${d.selectedScore??'n/a'}`,`best_expected=${d.bestAvailableScore??'n/a'}`].join('\n');}
